language: erlang
script: "make travis"
otp_release:
  - 21.0
  - 20.0
  - 19.2
  - 18.3
  - 17.5
before_script:
  - sudo service postgresql stop
  - sudo service mysql stop
  - sudo service memcached stop
