language: erlang
script: "make travis"
otp_release:
  - 23.0
  - 22.2
  - 21.0
  - 20.0
  - 19.3
  - 18.3
  - 17.5
  - 17.0
before_script:
  - sudo service postgresql stop
  - sudo service mysql stop
  - sudo service memcached stop
